### ISSUE TITLE
New logos

### ISSUE THREAD

**Issue by dalmore72** [Jasmeet181/mediaportal-cz-logos#2]
thanks for the super work you do

[cz.zip](https://github.com/Jasmeet181/mediaportal-cz-logos/files/155847/cz.zip)

**Comment by Jasmeet181** [comment]
Thanks. The glossy Duck TV HD logo I see on most other sites is like the existing one so I'll use that instead. I think that they're alternatives rather than new replacements, the glossy Duck TV logo was uploaded [here](https://www.facebook.com/ducktv/photos/a.167901526597103.53597.146844172036172/204487972938458/?type=3&theater) in 2011 for example and [HBO.cz ](http://www.hbo.cz/schedule) has flat logos in some places. The rest of the packs are on [Assembla](https://www.assembla.com/spaces/mediaportal/stream) in case you didn't know.
